name: pruebamarvel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  http: ^1.1.0
  pretty_http_logger: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - .env

  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: fonts/roboto-bold.ttf
          weight: 700
    - family: Roboto-Regular
      fonts:
        - asset: fonts/roboto-regular.ttf
          weight: 500
    - family: Roboto-Light
      fonts:
        - asset: fonts/roboto-light.ttf
          weight: 300
    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
